import Head from "next/head";
import {Header,Footer} from '../common';

export const Layout = ({ children }) => {
  return (
    <div className="layout">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
      <Footer />
    </div>
  );
};


